import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter, type Href } from 'expo-router';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, View } from 'react-native';

import {
  Button,
  Card,
  EmptyState,
  FadeIn,
  ScreenContainer,
  SectionHeader,
} from '@/components/ui';
import { colors, spacing, typography } from '@/constants/theme';
import { APP_ROUTES } from '@/navigation/routes';
import { useAuth } from '@/providers';
import { fetchCustomerQuoteBySession } from '@/services/inquiries';

function formatMoney(amount: number | null): string {
  if (amount === null || Number.isNaN(amount)) return '—';
  try {
    return new Intl.NumberFormat(undefined, {
      style: 'currency',
      currency: 'PKR',
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return String(amount);
  }
}

function getQuoteErrorMessage(error: unknown): string {
  const message = error instanceof Error ? error.message : '';
  if (message.includes('unauthorized_quote_access')) {
    return 'This quotation is not available for your account.';
  }
  if (message.includes('quote_not_available')) {
    return 'No quotation has been shared for this request yet.';
  }
  if (message.includes('quote_schema_missing')) {
    return 'Quotation access is not configured on the server yet. Run migration 019 in Supabase.';
  }
  return message || 'Unable to load quotation.';
}

export default function InquiryQuoteScreen() {
  const router = useRouter();
  const { sessionToken } = useAuth();
  const { id } = useLocalSearchParams<{ id: string }>();
  const inquiryId = Array.isArray(id) ? id[0] : id;

  const { data, isLoading, isError, error, refetch, isRefetching } = useQuery({
    queryKey: ['customer-quote', sessionToken, inquiryId],
    enabled: Boolean(sessionToken && inquiryId),
    queryFn: async () => {
      const result = await fetchCustomerQuoteBySession(sessionToken!, inquiryId!);
      if (result.error || !result.data) {
        throw result.error || new Error('quote_not_available');
      }
      return result.data;
    },
  });

  if (isLoading && !data) {
    return (
      <ScreenContainer title="Quotation" subtitle="Loading…">
        <View style={styles.centered}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Loading quotation…</Text>
        </View>
      </ScreenContainer>
    );
  }

  if (isError || !data) {
    return (
      <ScreenContainer title="Quotation" subtitle="Unavailable">
        <EmptyState
          icon="document-text-outline"
          title="Quotation unavailable"
          description={getQuoteErrorMessage(error)}
          actionLabel="Back to request"
          onActionPress={() =>
            router.replace(APP_ROUTES.inquiryDetail(inquiryId || '') as Href)
          }
        />
      </ScreenContainer>
    );
  }

  return (
    <ScreenContainer
      title={data.quotationNumber || 'Quotation'}
      subtitle="Shared by Logistix"
      headerRight={
        <Pressable
          accessibilityRole="button"
          onPress={() => router.back()}
          hitSlop={12}
        >
          <Text style={styles.backLink}>Back</Text>
        </Pressable>
      }
    >
      {isRefetching ? (
        <View style={styles.refreshRow}>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={styles.refreshText}>Refreshing…</Text>
        </View>
      ) : null}

      <FadeIn>
        <Card>
          <View style={styles.hero}>
            <View style={styles.heroIcon}>
              <Ionicons name="document-text-outline" size={28} color={colors.accent} />
            </View>
            <Text style={styles.heroTitle}>Your quotation is ready</Text>
            <Text style={styles.heroBody}>
              This is the same PDF generated by Logistix Sales. Open it to review the full
              commercial offer.
            </Text>
          </View>
        </Card>
      </FadeIn>

      <FadeIn delay={60}>
        <SectionHeader title="Summary" />
        <Card>
          <FactRow label="Quote #" value={data.quotationNumber || '—'} />
          <FactRow label="Total" value={formatMoney(data.totalAmount)} />
          <FactRow
            label="Date"
            value={
              data.quotationDate
                ? new Date(data.quotationDate).toLocaleDateString()
                : '—'
            }
          />
          <FactRow
            label="Valid until"
            value={
              data.expirationDate
                ? new Date(data.expirationDate).toLocaleDateString()
                : '—'
            }
          />
          <FactRow
            label="Payment terms"
            value={data.paymentTerms?.trim() || '—'}
            last={!data.customerNotes?.trim()}
          />
          {data.customerNotes?.trim() ? (
            <FactRow label="Notes" value={data.customerNotes.trim()} last />
          ) : null}
        </Card>
      </FadeIn>

      <View style={styles.actions}>
        <Button
          label="Open quotation PDF"
          fullWidth
          size="lg"
          onPress={() => void Linking.openURL(data.pdfUrl)}
        />
        <Button
          label="Contact sales"
          variant="outline"
          fullWidth
          onPress={() => router.push(APP_ROUTES.support as Href)}
        />
        <Button
          label="Refresh"
          variant="ghost"
          fullWidth
          onPress={() => refetch()}
        />
      </View>
    </ScreenContainer>
  );
}

function FactRow({
  label,
  value,
  last = false,
}: {
  label: string;
  value: string;
  last?: boolean;
}) {
  return (
    <View style={[styles.factRow, !last && styles.factBorder]}>
      <Text style={styles.factLabel}>{label}</Text>
      <Text style={styles.factValue}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    paddingVertical: spacing.huge,
  },
  loadingText: {
    ...typography.bodySmall,
    color: colors.textSecondary,
  },
  backLink: {
    ...typography.label,
    color: colors.accent,
  },
  refreshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  refreshText: {
    ...typography.caption,
    color: colors.textMuted,
  },
  hero: {
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  heroIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  heroTitle: {
    ...typography.h3,
    color: colors.text,
    textAlign: 'center',
  },
  heroBody: {
    ...typography.bodySmall,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  factRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  factBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  factLabel: {
    ...typography.caption,
    color: colors.textMuted,
    width: 110,
    flexShrink: 0,
    paddingTop: 2,
  },
  factValue: {
    ...typography.body,
    color: colors.text,
    flex: 1,
    minWidth: 0,
  },
  actions: {
    gap: spacing.md,
    marginTop: spacing.lg,
  },
});
