-- Legacy note: mobile app auth uses public.users (see 005+), not public.customers.
-- public.customers is owned by the logistix web schema (name, phone_number, lead_id, etc.).
-- Do not create or alter public.customers here — portal RPCs read the web table as-is.
